
# MakeFile 

# CS 480 Operating Systems
# Programming Assignment 1 / Chat Bot 
## Team Members 
# Name: Jeremiah Dobes
# RedID: 
# Edoras:

# Name: Anthony Ngo
# RedID: 825252396
# Edoras: cssc4410



# Makefile for bots program

# Compiler and compiler flags
CC = g++
CFLAGS = -std=c++11 -pthread

# Source files and object files
SRCS = bots.cpp
OBJS = $(SRCS:.cpp=.o)

# Target executable
TARGET = bots

# Rule to compile source files into object files
%.o: %.cpp
	$(CC) $(CFLAGS) -c $< -o $@

# Rule to link object files into the target executable
$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(TARGET)

# Clean rule to remove object files and executable
clean:
	rm -f $(OBJS) $(TARGET)